import { Metadata } from "next";
import { Pacifico } from "next/font/google";
import "./globals.css";

// Metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Load Pacifico font
const pacifico = Pacifico({
  weight: "400",
  subsets: ["latin"],
  style: "normal",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Apply the Pacifico font to the body */}
      <body className={pacifico.className}>
        <main>{children}</main>
      </body>
    </html>
  );
}